In [3]:
# Tensors are specialized data strucutre that are very similar to arrays and martricies. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model's paramters.

In [4]:
import torch
import numpy as np

In [5]:
data = [[1, 2], [3,4]]

x_data = torch.tensor(data)

print(type(data))
print(x_data)
x_data.shape

<class 'list'>
tensor([[1, 2],
        [3, 4]])


torch.Size([2, 2])

In [6]:
np_array = np.array(data)
print(type(np_array))
x_np = torch.from_numpy(np_array)
print(type(x_np))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [7]:
x_ones = torch.ones_like(x_data)
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [8]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.3295, 0.8924],
        [0.3531, 0.5356]]) 



In [9]:
x_data

tensor([[1, 2],
        [3, 4]])

In [10]:
x_data.dtype

torch.int64

In [11]:
x_rand.dtype

torch.float32

In [12]:
shape = (2, 3)

In [13]:
rand_tensor = torch.rand(shape)
print(rand_tensor)

tensor([[0.2698, 0.9877, 0.8297],
        [0.0685, 0.0672, 0.1730]])


In [14]:
ones_tensor = torch.ones(shape)
print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [15]:
zeros_tensor = torch.zeros(shape)

In [16]:
tensor = torch.rand(3,4)

In [17]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [18]:
#  Operations on Tensors

In [19]:
if torch.cuda.is_available():
  tensor = tensor.to("cuda")


In [20]:
# Tensor indexing

tensor = torch.rand(4, 4)
print(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1]=0

tensor([[0.9686, 0.0160, 0.5350, 0.4319],
        [0.6936, 0.2767, 0.4436, 0.4193],
        [0.9852, 0.0030, 0.2918, 0.1317],
        [0.0564, 0.6392, 0.2359, 0.7945]])
First row: tensor([0.9686, 0.0160, 0.5350, 0.4319])
First column: tensor([0.9686, 0.6936, 0.9852, 0.0564])
Last column: tensor([0.4319, 0.4193, 0.1317, 0.7945])


In [21]:
print(tensor)

tensor([[0.9686, 0.0000, 0.5350, 0.4319],
        [0.6936, 0.0000, 0.4436, 0.4193],
        [0.9852, 0.0000, 0.2918, 0.1317],
        [0.0564, 0.0000, 0.2359, 0.7945]])


In [22]:
# Joining Tensors

print(tensor)

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.9686, 0.0000, 0.5350, 0.4319],
        [0.6936, 0.0000, 0.4436, 0.4193],
        [0.9852, 0.0000, 0.2918, 0.1317],
        [0.0564, 0.0000, 0.2359, 0.7945]])
tensor([[0.9686, 0.0000, 0.5350, 0.4319, 0.9686, 0.0000, 0.5350, 0.4319, 0.9686,
         0.0000, 0.5350, 0.4319],
        [0.6936, 0.0000, 0.4436, 0.4193, 0.6936, 0.0000, 0.4436, 0.4193, 0.6936,
         0.0000, 0.4436, 0.4193],
        [0.9852, 0.0000, 0.2918, 0.1317, 0.9852, 0.0000, 0.2918, 0.1317, 0.9852,
         0.0000, 0.2918, 0.1317],
        [0.0564, 0.0000, 0.2359, 0.7945, 0.0564, 0.0000, 0.2359, 0.7945, 0.0564,
         0.0000, 0.2359, 0.7945]])


In [25]:
a = torch.rand(1,3)
b = torch.rand(1,2)


In [26]:
# Airthmetic Operations

In [27]:
tensor

tensor([[0.9686, 0.0000, 0.5350, 0.4319],
        [0.6936, 0.0000, 0.4436, 0.4193],
        [0.9852, 0.0000, 0.2918, 0.1317],
        [0.0564, 0.0000, 0.2359, 0.7945]])

In [28]:
tensor.T

tensor([[0.9686, 0.6936, 0.9852, 0.0564],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.5350, 0.4436, 0.2918, 0.2359],
        [0.4319, 0.4193, 0.1317, 0.7945]])

In [30]:
y1 = tensor @ tensor.T
print(y1)

tensor([[1.4110, 1.0902, 1.1672, 0.5240],
        [1.0902, 0.8536, 0.8680, 0.4769],
        [1.1672, 0.8680, 1.0730, 0.2291],
        [0.5240, 0.4769, 0.2291, 0.6900]])


In [31]:
y2 = tensor.matmul(tensor.T)

In [32]:
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[1.4110, 1.0902, 1.1672, 0.5240],
        [1.0902, 0.8536, 0.8680, 0.4769],
        [1.1672, 0.8680, 1.0730, 0.2291],
        [0.5240, 0.4769, 0.2291, 0.6900]])

In [33]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.9383, 0.0000, 0.2862, 0.1865],
        [0.4811, 0.0000, 0.1967, 0.1758],
        [0.9705, 0.0000, 0.0851, 0.0173],
        [0.0032, 0.0000, 0.0557, 0.6312]])

In [ ]:
# Single element tensors

agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

In [34]:
t1 = torch.tensor([[2,3],[4,5]])

In [36]:
t2 = torch.tensor([[1,2], [3,3]])

In [38]:
sum = t1.sum()

In [40]:
print(sum)
sum.item()

tensor(14)


14

In [41]:
2 * 2

4

In [46]:
print(type(tensor))
print(type(tensor.numpy()))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [47]:
a = tensor.numpy()

In [50]:
print(tensor)
print(a)

tensor([[1.9686, 1.0000, 1.5350, 1.4319],
        [1.6936, 1.0000, 1.4436, 1.4193],
        [1.9852, 1.0000, 1.2918, 1.1317],
        [1.0564, 1.0000, 1.2359, 1.7945]])
[[1.9686334 1.        1.5349867 1.4318606]
 [1.6936018 1.        1.4435624 1.4192946]
 [1.9851612 1.        1.2917788 1.1317018]
 [1.0564178 1.        1.2359276 1.7944653]]


In [49]:
tensor.add_(1)

tensor([[1.9686, 1.0000, 1.5350, 1.4319],
        [1.6936, 1.0000, 1.4436, 1.4193],
        [1.9852, 1.0000, 1.2918, 1.1317],
        [1.0564, 1.0000, 1.2359, 1.7945]])

In [43]:
a = 2
b = 3
a * b
c = a * b

In [37]:
print(t1)
print(t2)
print(t1*t2)

tensor([[2, 3],
        [4, 5]])
tensor([[1, 2],
        [3, 3]])
tensor([[ 2,  6],
        [12, 15]])


In [ ]:
# In place operations

In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

In [ ]:
# Bridge with NumPy

In [ ]:
# Tensor to NumPy array

t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

In [ ]:
# A change in the tensor reflects in the NumPy array.

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

In [ ]:
# NumPy array to Tensor

n = np.ones(5)
t = torch.from_numpy(n)